### ISSUE TITLE
Failed to parse network interface name because of vlan

### ISSUE THREAD

**Issue by chengyu-l** [IBM/SpectrumScaleTools#4]
Error ouput:

<img width="837" alt="Image" src="https://github.com/user-attachments/assets/ab5fcc13-6d7c-4494-8d4d-440afc64eed2" />

I use ubuntu 22.04, this is network interface:

<img width="642" alt="Image" src="https://github.com/user-attachments/assets/82991614-f770-45bc-ab76-5ba791580af3" />

the ` /etc/netplan/50-cloud-init.yaml`  file:

```yaml 
network:
    bonds:
        bond0:
            interfaces:
            - enp59s0f0np0
            - enp59s0f1np1
            mtu: 9000
            parameters:
                lacp-rate: fast
                mode: 802.3ad
                mii-monitor-interval: 100
                transmit-hash-policy: layer3+4
        bond1:
            interfaces:
            - enp134s0f0np0
            - enp134s0f1np1
            mtu: 9000
            parameters:
                lacp-rate: fast
                mode: 802.3ad
                mii-monitor-interval: 100
                transmit-hash-policy: layer3+4
    ethernets:
        enp134s0f0np0: {}
        enp134s0f1np1: {}
        enp59s0f0np0: {}
        enp59s0f1np1: {}
    version: 2
    vlans:
        bond0.1202:
            addresses:
            - 10.125.1.200/24
            id: 1202
            link: bond0
            mtu: 9000
            nameservers:
                addresses: []
                search: []
        bond1.1499:
            addresses:
            - 10.4.16.221/22
            id: 1499
            link: bond1
            mtu: 9000
            nameservers:
                addresses:
                - 114.114.114.114
                search: []
            routes:
            - to: 0.0.0.0/0
              via: 10.4.19.254
```
